// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: max-val/maxpb/max.proto

package maxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetMaxRequest) Reset() {
	*x = GetMaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_max_val_maxpb_max_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxRequest) ProtoMessage() {}

func (x *GetMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_max_val_maxpb_max_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxRequest.ProtoReflect.Descriptor instead.
func (*GetMaxRequest) Descriptor() ([]byte, []int) {
	return file_max_val_maxpb_max_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaxRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetMaxResponse) Reset() {
	*x = GetMaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_max_val_maxpb_max_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxResponse) ProtoMessage() {}

func (x *GetMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_max_val_maxpb_max_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxResponse.ProtoReflect.Descriptor instead.
func (*GetMaxResponse) Descriptor() ([]byte, []int) {
	return file_max_val_maxpb_max_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaxResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_max_val_maxpb_max_proto protoreflect.FileDescriptor

var file_max_val_maxpb_max_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x78, 0x2d, 0x76, 0x61, 0x6c, 0x2f, 0x6d, 0x61, 0x78, 0x70, 0x62, 0x2f,
	0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x27,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x45, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x78, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x6d, 0x61, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x61,
	0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_max_val_maxpb_max_proto_rawDescOnce sync.Once
	file_max_val_maxpb_max_proto_rawDescData = file_max_val_maxpb_max_proto_rawDesc
)

func file_max_val_maxpb_max_proto_rawDescGZIP() []byte {
	file_max_val_maxpb_max_proto_rawDescOnce.Do(func() {
		file_max_val_maxpb_max_proto_rawDescData = protoimpl.X.CompressGZIP(file_max_val_maxpb_max_proto_rawDescData)
	})
	return file_max_val_maxpb_max_proto_rawDescData
}

var file_max_val_maxpb_max_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_max_val_maxpb_max_proto_goTypes = []interface{}{
	(*GetMaxRequest)(nil),  // 0: max.GetMaxRequest
	(*GetMaxResponse)(nil), // 1: max.GetMaxResponse
}
var file_max_val_maxpb_max_proto_depIdxs = []int32{
	0, // 0: max.MaxService.GetMax:input_type -> max.GetMaxRequest
	1, // 1: max.MaxService.GetMax:output_type -> max.GetMaxResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_max_val_maxpb_max_proto_init() }
func file_max_val_maxpb_max_proto_init() {
	if File_max_val_maxpb_max_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_max_val_maxpb_max_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_max_val_maxpb_max_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_max_val_maxpb_max_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_max_val_maxpb_max_proto_goTypes,
		DependencyIndexes: file_max_val_maxpb_max_proto_depIdxs,
		MessageInfos:      file_max_val_maxpb_max_proto_msgTypes,
	}.Build()
	File_max_val_maxpb_max_proto = out.File
	file_max_val_maxpb_max_proto_rawDesc = nil
	file_max_val_maxpb_max_proto_goTypes = nil
	file_max_val_maxpb_max_proto_depIdxs = nil
}
