// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: max-val/maxpb/max.proto

package maxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MaxServiceClient is the client API for MaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaxServiceClient interface {
	// bi-di
	GetMax(ctx context.Context, opts ...grpc.CallOption) (MaxService_GetMaxClient, error)
}

type maxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxServiceClient(cc grpc.ClientConnInterface) MaxServiceClient {
	return &maxServiceClient{cc}
}

func (c *maxServiceClient) GetMax(ctx context.Context, opts ...grpc.CallOption) (MaxService_GetMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &MaxService_ServiceDesc.Streams[0], "/max.MaxService/GetMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &maxServiceGetMaxClient{stream}
	return x, nil
}

type MaxService_GetMaxClient interface {
	Send(*GetMaxRequest) error
	Recv() (*GetMaxResponse, error)
	grpc.ClientStream
}

type maxServiceGetMaxClient struct {
	grpc.ClientStream
}

func (x *maxServiceGetMaxClient) Send(m *GetMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maxServiceGetMaxClient) Recv() (*GetMaxResponse, error) {
	m := new(GetMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaxServiceServer is the server API for MaxService service.
// All implementations must embed UnimplementedMaxServiceServer
// for forward compatibility
type MaxServiceServer interface {
	// bi-di
	GetMax(MaxService_GetMaxServer) error
	mustEmbedUnimplementedMaxServiceServer()
}

// UnimplementedMaxServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMaxServiceServer struct {
}

func (UnimplementedMaxServiceServer) GetMax(MaxService_GetMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMax not implemented")
}
func (UnimplementedMaxServiceServer) mustEmbedUnimplementedMaxServiceServer() {}

// UnsafeMaxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaxServiceServer will
// result in compilation errors.
type UnsafeMaxServiceServer interface {
	mustEmbedUnimplementedMaxServiceServer()
}

func RegisterMaxServiceServer(s grpc.ServiceRegistrar, srv MaxServiceServer) {
	s.RegisterService(&MaxService_ServiceDesc, srv)
}

func _MaxService_GetMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxServiceServer).GetMax(&maxServiceGetMaxServer{stream})
}

type MaxService_GetMaxServer interface {
	Send(*GetMaxResponse) error
	Recv() (*GetMaxRequest, error)
	grpc.ServerStream
}

type maxServiceGetMaxServer struct {
	grpc.ServerStream
}

func (x *maxServiceGetMaxServer) Send(m *GetMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maxServiceGetMaxServer) Recv() (*GetMaxRequest, error) {
	m := new(GetMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaxService_ServiceDesc is the grpc.ServiceDesc for MaxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "max.MaxService",
	HandlerType: (*MaxServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMax",
			Handler:       _MaxService_GetMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "max-val/maxpb/max.proto",
}
